## RETRIEVING KEGG ID AND IDENTIFY PATHWAYS

In [1]:
import pandas as pd
import os 
import numpy as np
from scipy.stats import fisher_exact

In [2]:
#Opening the data

FARID_data = pd.read_csv("AnnotatedMetabolites.csv", sep =";", encoding='utf-8')
metabolome = pd.read_csv("metabolome.csv", sep =";", encoding='utf-8', header = None)
KEGG_data =  pd.read_csv("MAIN Pathways_Homo sapiens_KEGG.csv", sep =";", encoding='utf-8')

#Opening our test data
query_data =  pd.read_csv("Exemple_ligne_2.csv", sep = ';')
data = pd.read_csv("SIGNIFICANTS_1.csv", sep = ';') ; data

                   Timepoints
0                    Pyruvate
1                     Alanine
2  G.aminobutyricacid.Isomers
3                     Choline
4                      Serine

In [4]:
for k in range(0, len(data.columns))  :
    L = []
    #First step : retrieve the KEGG ID of the query list of metabolites
    for metabolite in data.iloc[:,k] :
        for i in range(0, len( FARID_data.iloc[:,0])) : 
            if metabolite == FARID_data.iloc[i,0] or metabolite == FARID_data.iloc[i,1] :
                L.append(FARID_data.iloc[i,2])
                
    #Now we do have the KEGG ID's. Let's retrieve the pathways !
    current_path = ""

    M = []

    for j in range(0, len( KEGG_data["Pathways"])) :
        if KEGG_data.iloc[j,0] != current_path :

            if len(M) > 1 : 
                ligne = f"{M[0]};{count/count_data * 100};{count};{','.join(M[1:len(M)])};{count_data}\n"
                #print(ligne)
        
            current_path = KEGG_data.iloc[j,0]

            count_data = 1
            count = 0
            M = [current_path]
            #print(current_path)
            for element in L :
                if KEGG_data.iloc[j,2] == element :
                    M.append(KEGG_data.iloc[j,2])
                    count += 1
        else :
            count_data += 1
            for element in L :
                if KEGG_data.iloc[j,2] == element :
                    M.append(KEGG_data.iloc[j,1])
                    count += 1
                    #print(M)
                    #print(count)
    
print(L)

['C00022', 'C00041', 'C00114', 'C00065']

### RETRIEVING INFORMATION FOR FISHER EXACT TEST DATA

In [55]:
for k in range(0, len(data.columns))  :
    P = []
    #First step : retrieve the KEGG ID of the query list of metabolites
    for metabolite in data.iloc[:,k] :
        for i in range(0, len( FARID_data.iloc[:,0])) : 
            if metabolite == FARID_data.iloc[i,0] or metabolite == FARID_data.iloc[i,1] :
                P.append(FARID_data.iloc[i,2])

In [63]:
non_significant = []

index_metabo = [i for i in range(5,16)]
for total_met in  query_data.columns[index_metabo] :
    for j in range(0, len( FARID_data.iloc[:,0])) : 
        if total_met == FARID_data.iloc[j,0] or total_met == FARID_data.iloc[j,1] :
                non_significant.append(FARID_data.iloc[j,2])


for total_met in non_significant :
    for metabolite in P :
        if metabolite == total_met :
            non_significant.remove(total_met)

In [124]:
#First step : retrieve the KEGG ID of the query list of metabolites
for k in range(0, len(data.columns))  :
    L = []
    for metabolite in data.iloc[:,k] :
        for i in range(0, len( FARID_data.iloc[:,0])) : 
            if metabolite == FARID_data.iloc[i,0] or metabolite == FARID_data.iloc[i,1] :
                L.append(FARID_data.iloc[i,2])



#retrieving the ID of the non significant metabolites
all = [met for met in metabolome.iloc[:,0]]

#total of our metabolites of our experiment
N = len(all)

#List of the non significant metabolites in our metabolome
non_significant = []
for i in range(0,len(all)):
    if all[i] not in L :
        non_significant.append( all[i])
                
#Now we do have the KEGG ID's. Let's retrieve the pathways !
current_path = ""

#Not significant who are in the pathway
P = []

#Significant who are in the pathway
M = []

for j in range(0, len( KEGG_data["Pathways"])) :
    if KEGG_data.iloc[j,0] != current_path :

        if len(M) > 1 : 
            #Preparation de la table de contingence pour le fisher exact test
                
            #x = count
            m_x = count_0 - count
            k_x = len(L) - count
            N_m_k_x = N - count_0  -  k_x

            print(f"{current_path} : {count}/{count_0}")

            table = np.array([[count, m_x], [k_x, N_m_k_x]])
            res = fisher_exact(table, alternative='greater')

            print(res.pvalue)


            #ligne = f"{M[0]};{res.pvalue};{count}//{count_0};{','.join(M[1:len(M)])}\n"
        
        current_path = KEGG_data.iloc[j,0]

        count_data = 1
        count = 0
        count_0 = 0
        M = [current_path]
        #print(current_path)
        for element in L :
            if KEGG_data.iloc[j,2] == element :
                M.append(KEGG_data.iloc[j,2])
                count += 1
        for element in all :
            if KEGG_data.iloc[j,2] == element :
                count_0 += 1
                
    else :
        count_data += 1
        for element in L :
            if KEGG_data.iloc[j,2] == element :
                M.append(KEGG_data.iloc[j,1])
                count += 1
                #print(M)
                #print(count)
        for element in all :
            if KEGG_data.iloc[j,2] == element :
                count_0 += 1

Alanine, aspartate and glutamate metabolism - Homo sapiens (human) : 2/14
0.006054684801137614
Aminoacyl-tRNA biosynthesis - Homo sapiens (human) : 2/18
0.010047163945114209
Arginine and proline metabolism - Homo sapiens (human) : 1/16
0.14536139150894709
Biosynthesis of amino acids - Homo sapiens (human) : 2/33
0.032985685433198346
Carbon metabolism - Homo sapiens (human) : 2/26
0.020784577157551064
Citrate cycle (TCA cycle) - Homo sapiens (human) : 1/8
0.07482030976741759
Cysteine and methionine metabolism - Homo sapiens (human) : 2/10
0.0030333914759637674
Glycerophospholipid metabolism - Homo sapiens (human) : 1/5
0.047273206135901205
Glycine, serine and threonine metabolism - Homo sapiens (human) : 3/12
7.214681975658947e-05
Glycolysis / Gluconeogenesis - Homo sapiens (human) : 1/10
0.09285020305470579
Glyoxylate and dicarboxylate metabolism - Homo sapiens (human) : 2/10
0.0030333914759637674
Metabolic pathways - Homo sapiens (human) : 4/187
0.03972521704601102
One carbon pool by folate - Homo sapiens (human) : 1/7
0.0657052389276877
Purine metabolism - Homo sapiens (human) : 1/31
0.2666687216773706
Pyruvate metabolism - Homo sapiens (human) : 1/12
0.11061527938466408
Selenocompound metabolism - Homo sapiens (human) : 1/1
0.009592326139088728
Sphingolipid metabolism - Homo sapiens (human) : 1/2
0.0191154768492898
Tyrosine metabolism - Homo sapiens (human) : 1/6
0.05652298083361091

In [122]:
for e in L :
    print (e)

C00022
C00041
C00114
C00065

In [129]:
table = np.array([[3, 9], [1,374]]) ; table
res = fisher_exact(table, alternative='greater') ; res.pvalue

9.019302382960654e-05

### RETRIEVING KEGG ID FOR A QUERY LIST OF METABOLITES

In [22]:
data = pd.read_csv("Query_list.csv", sep = ';', encoding = 'latin1', header = None ) ; data

                                                     0
0    1-Methyluric acid_7-Methyluric acid_3-Methylur...
1                           2_O_Methylcytidine_Isomers
2                     4_Hydroxy_3_MethoxybenzylAlcohol
3                     4_Hydroxy_3_MethoxybenzylAlcohol
4                                  8_AminocaprylicAcid
..                                                 ...
171                                          Urocanate
172                                 Alpha_Aminoadipate
173                                 Alpha_Aminoadipate
174     N Acetyl D Allo Isoleucine_N Acetyl L Leucine
175     N Acetyl D Allo Isoleucine_N Acetyl L Leucine

[176 rows x 1 columns]

In [28]:
with open("return.csv", "w", encoding = "latin1" ) as file :
    for metabolite in data.iloc[:,0] :
        a = None
        for i in range(0, len( FARID_data.iloc[:,0])) :
            if a == None : 
                if metabolite == FARID_data.iloc[i,0] or metabolite == FARID_data.iloc[i,1] :
                    a = FARID_data.iloc[i,2] 
        if a != None :
            file.write(f"{metabolite};{a}\n")
        else :
            file.write(f"{metabolite};NA\n")

In [30]:
FARID_data

,MetaboliteName,KEGG_Pathways_Total_Metabolites,KEGG.ID,CommonName,CAS,PubChem,ChEBI,mzPos,mzNEG,RT,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,Guanidine,NaN,C17349,Guanidine; Carbamidine,113-00-8,135626098,NaN,60.05562,58.04107,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Urea,Urea,C00086,Urea; Carbamide,57-13-6,3386,16199,61.03964,59.02509,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Imidazole,NA,C01589,""Imidazole; Glyoxaline;"" 1","3-Diazole""""",288-32-4,4744,16069,69.04472,67.03017,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trimethylamine oxide,NaN,C01104,Trimethylamine N-oxide; (CH3)3NO,1184-78-7,4338,15724,75.06787,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Glycine,Glycine,C00037,Glycine; Aminoacetic acid; Gly,56-40-6,3339,15428,76.0393,74.02475,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,Acetyl-CoA,Acetyl-CoA,C00024,Acetyl-CoA; Acetyl coenzyme A,72-89-9,3326,15351,810.13305,808.1185,6.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656,1,2-dipalmitoyl-sn-glycero-3-phospho-(1'-myo-ino...,NaN,NaN,NaN,NaN,NaN,NaN,828.55965,826.5451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
657,Methylmalonyl coenzyme A,NaN,C02557,Methylmalonyl-CoA; Methylmalonyl coenzyme A; 2...,1264-45-5,5558,16625,868.13853,866.12398,1.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,1,2-di-(9Z-octadecenoyl)-sn-glycero-3-(cytidine ...,NaN,NaN,NaN,NaN,NaN,NaN,1040.60597,1038.59141,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,Tannic acid,NaN,C13452,Tannic acid,1401-55-4,586192,75211,1701.18025,1699.1657,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN